app_mahasiswa/urls.py
from django.conf.urls import url
from .views_base import *
from .views_friends import search_user, friends_index
from .views_login import *
from .views_profile import *
from .views_riwayat import *
from .views_status import *
from kirito.custom_auth import auth_login, auth_logout

#url for app
urlpatterns = [
    # base urls
    url(r'^$', index, name='index'),

    # login urls
    url(r'^login/$', login_index, name='login'),

    # profile urls
    url(r'^profile/$', profile_index, name='profile'),
    url(r'^profile/edit/$', edit_profile_index, name='edit-profile'),
    url(r'^profile/save/$', save_profile, name='save-profile'),

    # riwayat urls
    url(r'^riwayat/$', riwayat_index, name='riwayat'),

    # status urls
    url(r'^status/$', status_index, name='status'),
    url(r'^status/add_status/$', add_status, name='add_status'),
    url(r'^status/delete_status/$', delete_status, name='delete_status'),

    # friends urls
    url(r'^friends/$', friends_index, name='friends'),
    url(r'^search_user/$', search_user, name='search_user'),
    url(r'^auth_login/$', auth_login, name='auth_login'),
    url(r'^auth_logout/$', auth_logout, name='auth_logout')
]

kirito/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import app_mahasiswa.urls as mahasiswa

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mahasiswa/', include(mahasiswa, namespace='mahasiswa')),
    url(r'^$', RedirectView.as_view(url="/mahasiswa/", permanent="False"), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_mahasiswa/models.py
from django.db import models

# Create your models here.
class Skill(models.Model):
    skill_name = models.TextField()
    expertness = models.IntegerField()

class Mahasiswa(models.Model):
    npm = models.CharField('Student ID', max_length=20, primary_key=True)
    name = models.CharField('Name', max_length=200)
    email = models.TextField()
    description = models.TextField()
    linkedin_url = models.TextField()
    location = models.TextField(default="")
    picture_url = models.TextField(default="/static/img/Unknown.jpg")
    skills = models.ManyToManyField(Skill)
    show_score = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Status(models.Model):
    status = models.TextField(max_length=140)
    date = models.DateTimeField(auto_now_add=True)
    penulis = models.ForeignKey(Mahasiswa, related_name = 'stats')

app_mahasiswa/forms.py
from django import forms

class Add_Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form_control',
        'style' : 'resize:none',
        'rows' : '3',
    }
    status = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, label='', max_length=140)

app_mahasiswa/templates/friends.html
{% extends "base.html" %}

{% load staticfiles %}

{% block meta %}
<meta name="description" content="Project-Kirito: Cari Mahasiswa">
<meta name="author" content="Kelompok 9 PPW Kelas E">
{% endblock %}

{% block title %}Project-Kirito: Cari Mahasiswa{% endblock %}

{% block stylescript_app %}<link rel=stylesheet href="{% static 'css/friends.css' %}">{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div style="margin: -40px 20px 20px 20px">
    <form action="{% url 'mahasiswa:search_user' %}" method="GET">
        <label for="query"> SEARCH </label>
        <input type="text" id="query" name="query" required>
        <select name="attribute">
            <option value="npm">NPM</option>
            <option value="nama">Nama</option>
            <option value="angkatan">Angkatan</option>
            <option value="keahlian">Keahlian</option>
            <option value="level">Level</option>
        </select>
        <input type="submit" class="btn btn-default">
    </form>
</div>

<!-- testing purposes. please delete later. -->
<div class="container">
    <div class="row">
        <div class="p-3 align-self-center col-md-4">
            {% for user in user_list %}
            <div class="card">
                <div class="row">
                    <div class="col-md-12">
                        <img class="img-fluid d-block" src="{{ user.picture_url }}"> </div>
                    </div>
                    <div class="card-block p-2">
                        <h3>{{ user.name }}</h3>
                        <hr>
                        <p>{%if user.description%} {{ user.description }} {%else%} No description {% endif %}
                            <br> </p>
                        </div>
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td>NPM</td>
                                    <td>{{ user.npm }}</td>
                                </tr>
                                <tr>
                                    <td>Keahlian
                                        <br> </td>
                                        <td>{%if user.skills.all%} {%for skill in user.skills.all%} <p class="skill{{ skill.expertness }}"> {{ skill.skill_name }} {%endfor%}</p> {%else%} <p>No experties</p> {%endif%}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endblock %}

{% block footer %}
<script src="{% static 'js/friends.js' %}"/>
{% endblock %}

app_mahasiswa/templates/login-mahasiswa.html
{% extends "base.html" %}
{% load staticfiles %}
{% block meta %}
    <meta name="description" content="Project-Kirito: Login Mahasiswa">
    <meta name="author" content="Kelompok 9 PPW Kelas E">
{% endblock %}
{% block title %}Project-Kirito: Login using CSUI Account{% endblock %}
{% block stylescript_app %}<link rel=stylesheet href="{% static 'css/login.css' %}">{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'mahasiswa:auth_login' %}" method="POST">
                {% csrf_token %}
                {% for message in messages %}{% if message.level_tag == "warning" %}
                    <div class="alert alert-warning alert-dismissable text-center">{{message}}</div>
                {% endif %}{% endfor %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" id="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% if user_login %}<p class="copyright">Currently logged in: {{user_login}}</p>
    {% else %}{% include "partials/footer.html" %}{% endif %}
{% endblock %}

app_mahasiswa/templates/mahasiswa-base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block meta %}
    <meta name="description" content="Project-Kirito: Dashboard Mahasiswa">
    <meta name="author" content="Kelompok 9 PPW Kelas E">
{% endblock %}
{% block title %}Project-Kirito: Dashboard of {{user_login}}{% endblock %}
{% block stylescript_app %}{% endblock %}
{% block header %}{% include "partials/header.html" %}{% endblock %}
{% block content %}
<div class="pojok-kanan"></div>
<div class="container">
    <div class="card" id="profile-panel">
        <div class="card-header" id="main-panel-heading">
            {% if login %}
            <h4>Welcome, <b>{{mahasiswa.name}}!</b></h4>
            {% else %}
            <h4>Welcome!</h4>
            {% endif %}
        </div>
        <div class="card-block">
            {% if login %}
                <img class="profile profile-l float-left" style="margin:10px 20px" src="{{mahasiswa.picture_url}}">
            {% else %}
            <img class="profile profile-l float-left" style="margin:10px 20px" src="{% static 'img/Unknown.jpg' %}">
            {% endif %}
            <div class="card-text" style="margin:20px">
                {% if mahasiswa.description %}"{{mahasiswa.description}}"{% else %}<i>I have no description.</i>{% endif %}
            </div>
        </div>
        <div class="card-footer">
            {% if login %}
            <a href="{% url 'mahasiswa:auth_logout' %}" class="btn btn-sm btn-danger float-right" onclick="return confirm('Exit?')">Logout</a>
            {% else %}
            <a href="{% url 'mahasiswa:login' %}" class="btn btn-sm btn-success float-right" >Login</a>
            {% endif %}
        </div>
    </div>

    <!-- Error messages -->
    {% for message in messages %}{% if message.level_tag == "danger" %}
        <div class="alert alert-{{message.level_tag}} alert-dismissable text-center">{{message}}</div>
    {% endif %}{% endfor %}

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        {% if login %}
        <li role="presentation" aria-controls="home" class="nav-item">
            <a class="nav-link{% if login %} active{% endif %}" href="#profile" role="tab" data-toggle="tab">Profile</a>
        </li>
        <li role="presentation" aria-controls="home" class="nav-item">
            <a class="nav-link" href="#riwayat" role="tab" data-toggle="tab">Academic</a>
        </li>
        {% endif %}
        <li role="presentation" aria-controls="home" class="nav-item">
            <a class="nav-link{% if not login %} active{% endif %}" href="#status" role="tab" data-toggle="tab">Status</a>
        </li>
        {% if login %}
        <li role="presentation" aria-controls="home" class="nav-item">
            <a class="nav-link" href="#friends" role="tab" data-toggle="tab">Friends</a>
        </li>
        {% endif %}
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        {% if login %}
        <iframe role="tabpanel" class="tab-pane fade in out active show" id="profile" src='{% url "mahasiswa:profile" %}'></iframe>
        <iframe role="tabpanel" class="tab-pane fade in out" id="riwayat" src='{% url "mahasiswa:riwayat" %}'></iframe>
        {% endif %}
        <iframe role="tabpanel" class="tab-pane fade in out" id="status" src='{% url "mahasiswa:status" %}'></iframe>
        {% if login %}
        <iframe role="tabpanel" class="tab-pane fade in out" id="friends" src='{% url "mahasiswa:friends" %}'></iframe>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block footer %}{% include "partials/footer.html" %}{% endblock %}

app_mahasiswa/templates/profile-edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% block meta %}
    <meta name="description" content="Project-Kirito: Dashboard Mahasiswa">
    <meta name="author" content="Kelompok 9 PPW Kelas E">
{% endblock %}
{% block title %}Project-Kirito: Dashboard of {{user_login}}{% endblock %}
{% block stylescript_app %}{% endblock %}
{% block stylescript_page %}
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key:   81cwnsubg1szbc
        onLoad:    onLinkedInLoad
        authorize: true
        lang:      en_US
    </script>
{% endblock %}
{% block header %}{% include "partials/header.html" %}{% endblock %}
{% block content %}
<div class="container">
    <section name="header">
        <div class="card" id="profile-panel">
            <div class="card-header" id="main-panel-heading">
                <h4>Edit Profile of <b>{{mahasiswa.name}}</b></h4>
            </div>
            <div class="card-block">
                <img style="margin:10px 20px" id="profile-picture" class="profile profile-xl float-left" style="margin:10px 20px" src="{{mahasiswa.picture_url}}">
                <div id="user-description" class="card-text" style="margin:20px">
                    {% if mahasiswa.description %}"{{mahasiswa.description}}"{% else %}<i>I have no description.</i>{% endif %}
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'mahasiswa:auth_logout' %}" class="btn btn-sm btn-danger float-right" style="margin-left: 5px" onclick="return confirm('Exit?')">Logout</a>
                <a href="{% url 'mahasiswa:index' %}" class="btn btn-sm btn-warning float-right" onclick="return confirm('Are you sure?')">Discard</a>
                <a class="btn btn-sm btn-success float-right" style="margin-right:5px" onclick="saveProfile()">Save</a>
            </div>
        </div>

        <!-- Error messages -->
        {% for message in messages %}{% if message.level_tag == "danger" %}
            <div class="alert alert-{{message.level_tag}} alert-dismissable text-center">{{message}}</div>
        {% endif %}{% endfor %}
    </section>

    <section name="details">
        <h5><b>LinkedIn</b></h5>
        <div id="show-score" class="float-right">
            Show scores? <select id="show-score-input" value={% if mahasiswa.show_score %}1{% else %}0{% endif %}>
                <option value=0 {% if not mahasiswa.show_score %}selected="selected"{% endif %}>No</option>
                <option value=1 {% if mahasiswa.show_score %}selected="selected"{% endif %}>Yes</option>
            </select>
        </div>
        <div id="linkedin-data">
            <script type="in/Login"></script>
            {% if mahasiswa.linkedin_url %}
                <br>
                Name: {{mahasiswa.name}}<br>
                Email: {{mahasiswa.email}}<br>
                Location: {{mahasiswa.location}}<br>
                LinkedIn: <a href='{{mahasiswa.linkedin_url}}'>{{mahasiswa.linkedin_url}}</a><br>
            {% endif %}
        </div>
    </section>
    <hr>
    <h5><b>Skills</b></h5>
    <ol id="skills-list">
        {% if mahasiswa_skills %}
            {% for skill in mahasiswa_skills %}
                <li class="old-skill" id="li-old-{{skill.id}}">
                    <input class="skill-input" name="skill" id="skill-{{skill.id}}" value="{{skill.skill_name}}">
                    Level:
                    <select class="level-input" name="level" id="level-{{skill.id}}" value={{skill.expertness}}>
                        <option value=1 {% if skill.expertness == 1 %}selected="selected"{% endif %}>Beginner</option>
                        <option value=2 {% if skill.expertness == 2 %}selected="selected"{% endif %}>Intermediate</option>
                        <option value=3 {% if skill.expertness == 3 %}selected="selected"{% endif %}>Advanced</option>
                        <option value=4 {% if skill.expertness == 4 %}selected="selected"{% endif %}>Expert</option>
                        <option value=5 {% if skill.expertness == 5 %}selected="selected"{% endif %}>Legend</option>
                    </select>
                    <input class="skill-id" type="hidden" name="id" id="old-{{skill.id}}" value="{{skill.id}}">
                    <button class="skill-del" id="del-{{skill.id}}" onclick="removeSkillField('{{skill.id}}')">x</button>
                </li>
            {% endfor %}
        {% else %}
            <li class="new-skill" id="li-new-0">
                <input class="skill-input" name="skill" id="skill-new-0">
                Level:
                <select class="level-input" name="level" id="level-new-0">
                    <option value=1>Beginner</option>
                    <option value=2>Intermediate</option>
                    <option value=3>Advanced</option>
                    <option value=4>Expert</option>
                    <option value=5>Legend</option>
                </select>
                <input class="skill-id" type="hidden" name="id" id="new-0" value="new">
            </li>
        {% endif %}
    </ol>
    <button class="btn btn-default" id="add-skill" onclick="addSkillField()">Tambah Keahlian</button>
</div>
{% endblock %}
{% block footer %}{% include "partials/footer.html" %}{% endblock %}
{% block scripts_page %}
<script type="text/javascript">
    var dict = {};
    var removeSkills = {};
    var changeSkills = {};
    var addSkills = {};
    var newSkillIndex = 1;

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                // Only send the token to relative URLs i.e. locally.
                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            }
        }
   });

    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log(data);
        html = "Name: " + data.formattedName + "<br>" +
                "Email: " + data.emailAddress + "<br>" +
                "Location: " + data.location.name + "<br>" +
                "LinkedIn: <a href='" + data.publicProfileUrl + "'>" + data.publicProfileUrl + "</a><br>"+
                '<a class="btn btn-sm btn-danger float-right" style="margin-left: 5px" onclick="return confirm(\'Logout LinkedIn?\')">Logout LinkedIn</a><br>';
        $("#linkedin-data").html(html)
        $("#user-description").html('"' + data.summary + '"')
        $("#profile-picture").attr("src", data.pictureUrl)
        dict = data;
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~:(id,formatted-name,location,summary,picture-url,public-profile-url,email-address)").result(onSuccess).error(onError);
    }

    // Add new skill field
    function addSkillField() {
        $("#skills-list").append('<li class="new-skill" id="li-new-'+newSkillIndex+'">' +
                                '<input class="skill-input" name="skill" id="skill-new-'+newSkillIndex+'">' +
                                ' Level: ' +
                                '<select class="level-input" name="level" id="level-new-'+newSkillIndex+'">' +
                                    '<option value=1>Beginner</option>' +
                                    '<option value=2>Intermediate</option>' +
                                    '<option value=3>Advanced</option>' +
                                    '<option value=4>Expert</option>' +
                                    '<option value=5>Legend</option>' +
                                '</select>' +
                                '<input class="skill-id" type="hidden" name="id" id="new-'+newSkillIndex+'" value="new">' +
                                ' <button class="skill-del" id="del-new-'+newSkillIndex+'" onclick="removeSkillField(\'new-'+newSkillIndex+'\')">x</button>' +
                            '</li>');
        newSkillIndex++;
    }

    // Remove a skill field
    function removeSkillField(id) {
        if (!id.includes("new")) {
            intId = parseInt(id);
            removeSkills[intId] = {"name":$("#li-old-"+id).children(".skill-input").val(),
                                "level":$("#li-old-"+id).children(".level-input").val()};
            $("#li-old-"+id).remove();
        }
        else $("#li-"+id).remove();
    }

    // Save the profile
    var saveProfile = function() {
        $("#skills-list").children('li').each(function() {
            if ($(this).attr('class') === "old-skill") {
                changeSkills[$(this).children(".skill-id").val()] = {"name":$(this).children(".skill-input").val(),
                                                                    "level":$(this).children(".level-input").val()};
            } else if ($(this).attr('class') === "new-skill") {
                addSkills[$(this).children(".skill-input").val()] = $(this).children(".level-input").val();
            }
        });

        addSkillsJson = JSON.stringify(addSkills);
        removeSkillsJson = JSON.stringify(removeSkills);
        changeSkillsJson = JSON.stringify(changeSkills);
        showScores = $("#show-score-input").val();

        $.ajax({
            method: 'POST',
            url: '{% url "mahasiswa:save-profile" %}',
            data: {formattedName:dict.formattedName, location:JSON.stringify(dict.location), show_score:showScores,
                    publicProfileUrl:dict.publicProfileUrl, pictureUrl:dict.pictureUrl,
                    summary:dict.summary, emailAddress:dict.emailAddress,
                    add_skills:addSkillsJson, remove_skills:removeSkillsJson, change_skills:changeSkillsJson},
            success: function (meow) {
                alert("Success!");
                document.location.reload("true");
            },
            error: function (error) {
                alert("Failed!");
            }
        });

        removeSkills = {}
        changeSkills = {}
        addSkills = {}
    }

    // Logout LinkedIn
    function closeSession(){
        IN.User.logout();
        document.location.reload("true");
    }
</script>
{% endblock %}

app_mahasiswa/templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block meta %}
    <meta name="description" content="Project-Kirito: Profil Mahasiswa">
    <meta name="author" content="Kelompok 9 PPW Kelas E">
{% endblock %}
{% block title %}Project-Kirito: Profile of {{user_login}}{% endblock %}
{% block stylescript_app %}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<div style="margin: -40px 20px 20px 20px">
    Name: {{mahasiswa.name}}<br>
    NPM: {{mahasiswa.npm}}<br>
    Skills: {% if mahasiswa_skills %}<ul>
        {% for skill in mahasiswa_skills %}
            <li>{{skill.skill_name}}, {% if skill.expertness == 1 %}Beginner{% elif skill.expertness == 2 %}Intermediate{% elif skill.expertness == 3 %}Advanced{% elif skill.expertness == 4 %}Expert{% else %}Legend{% endif %}</li>
        {% endfor %}</ul>{% else %}<i>Kosong</i><br>{% endif %}
    Email: {% if mahasiswa.email %}{{mahasiswa.email}}{% else %}<i>Kosong</i>{% endif %}<br>
    Location: {% if mahasiswa.location %}{{mahasiswa.location}}{% else %}<i>Kosong</i>{% endif %}<br>
    LinkedIn Profile: {% if mahasiswa.linkedin_url %}{{mahasiswa.linkedin_url}}{% else %}<i>Kosong</i>{% endif %}<br>
</div>
{% endblock %}
{% block footer %}{% endblock %}

app_mahasiswa/templates/riwayat.html
{% extends "base.html" %}
{% load staticfiles %}
{% block meta %}
    <meta name="description" content="Project-Kirito: Riwayat Mahasiswa">
    <meta name="author" content="Kelompok 9 PPW Kelas E">
{% endblock %}
{% block title %}Project-Kirito: Riwayat of {{user_login}}{% endblock %}
{% block stylescript_app %}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<style>
table {
    border-collapse: collapse;
    width: 100%;
	border : none;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>
<div style="margin: -40px 20px 20px 20px">
    <!-- Fill Something Here -->
	<table id = "hehe" style="">
	</>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>

	var dataGet;

	$.ajax({
        method: "GET",
        url: 'https://private-e52a5-ppw2017.apiary-mock.com/riwayat',
        data: {},
        dataType: 'json',
        success: function (response) {
			console.log(response)
			for (inc in response){
				dataGet = response[inc];
				console.log(dataGet)
				if( '{{mahasiswa.show_score}}' == 'True'){
					html = "<tr>" +
								"<td><b>"+ dataGet.kelas.nm_mk_cl.nm_mk +"</b></td>"+
								"<td><b>"+ dataGet.nilai +"</b></td>"+
							"</tr>";
				}
				else{
					try{
					html = "<tr>" +
								"<td><b>"+ dataGet.kelas.nm_mk_cl.nm_mk +"</b></td>"+
								"<td><b>Dirahasiakan</b></td>"+
							"</tr>";
					}
					catch(err){
					html = "";
					}
				}
				$("#hehe").append(html)
			}
		},
	});
</script>
{% endblock %}
{% block footer %}{% endblock %}

app_mahasiswa/templates/status.html
{% extends "base.html" %}
{% load staticfiles %}
{% block meta %}
    <meta name="description" content="Project-Kirito: Halaman Status Mahasiswa">
    <meta name="author" content="Kelompok 9 PPW Kelas E">
{% endblock %}
{% block title %}Project-Kirito: {{user_login}}'s Status{% endblock %}
{% block stylescript_app %}<link rel=stylesheet href="{% static 'css/status.css' %}">
{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<div class="container" style="margin: -40px 20px 20px 20px">
    <!-- Fill Something Here -->
		<div >
			{% if login %}
			<form method="POST" id="add_status" action="add_status/">
			{% csrf_token %}
				{{ add_status_form }}
				<br>
				<div class="button_success">
					<button type="submit" class="button btn-success">Submit</button>
				</div>
			</form>
			{% endif %}
		</div>
		{% block content_page %}
			<p>
				{% for status_message in status reversed %}
					<div class="container_status">
						{% if login %}
						<form class="status_delete" action="delete_status/" method="POST" align="right">
							{% csrf_token %}
							<input type="hidden" name="status_id" value="{{ status_message.id }}" />
							<input type="submit" value="x">
						</form>
						{% endif %}
						<p>{{ status_message.status }}</p>
						<span class="name-left"> by
						{{ status_message.penulis.name }}</span>
						<span class="time-right">{{ status_message.date }}</span>
					</div>
				{% endfor %}
			</p>
		</div>
		{% endblock %}
{% endblock %}
{% block footer %}{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang=en>
	<head>
		<meta charset=UTF-8>
		<meta name=viewport content="width=device-width, initial-scale=1.0">
		<meta name=viewport content="width=device-width, initial-scale=1">
		<meta http-equiv=X-UA-Compatible content="IE=edge">
		<meta name="author" content="Kelompok 9 PPW E Gasal 2017/2018">
		{% block meta %}{% endblock %}

		{% block stylescript %}
		<link rel=stylesheet href="{% static 'css/bootstrap-4.0.0beta2.min.css' %}">
		{% endblock %}
		<link rel=stylesheet href="{% static 'css/base.css' %}">
        <link rel=stylesheet id="theme-css" href="{% static 'css/theme-dark.css' %}">
        {% block stylescript_app %}{% endblock %}
        {% block stylescript_page %}{% endblock %}

		<title>{% block title %}Welcome to Project Dio Brando!{% endblock %} - Project DioBrando</title>
		<style>{% block style %}{% endblock %}</style>
</head>
<body>
	<div class="main-container">
		<header>
			{% block header %}{% endblock %}
		</header>
		<content>
			<div class="content-out">{% block content %}{% endblock %}</div>
		</content>
		<footer>
			{% block footer %}{% endblock %}
		</footer>
	</div>
</body>
{% block scripts %}
	<script type=application/javascript src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script type=application/javascript src="{% static 'js/popper.min.js' %}"></script>
	<script type=application/javascript src="{% static 'js/bootstrap-4.0.0beta2.min.js' %}"></script>
    <script>
    themeKey = "theme";

    function switchTheme(themeName) {
        var name = "dark";
        var nav = document.getElementById("navbar");
        var stylesheet = null;
        if (themeName == null) {
            var storedName = localStorage.getItem(themeKey);
            if (storedName != null)
                name = storedName;
            if (name == "dark") {
                stylesheet = "{% static 'css/theme-dark.css' %}";
                if (nav != null) {
                    nav.classList.remove('navbar-light');
                    nav.classList.add('navbar-dark');
                }
            } else {
                stylesheet = "{% static 'css/theme-light.css' %}";
                if (nav != null) {
                    nav.classList.remove('navbar-dark');
                    nav.classList.add('navbar-light');
                }
            }
        } else if (themeName == "dark") {
            name = themeName;
            stylesheet = "{% static 'css/theme-dark.css' %}";
            localStorage.setItem(themeKey, name);
            if (nav != null) {
                nav.classList.remove('navbar-light');
                nav.classList.add('navbar-dark');
            }
        } else {
            name = themeName;
            stylesheet = "{% static 'css/theme-light.css' %}";
            localStorage.setItem(themeKey, name);
            if (nav != null) {
                nav.classList.remove('navbar-dark');
                nav.classList.add('navbar-light');
            }
        }
        document.getElementById("theme-css").setAttribute("href", stylesheet);
    }
    </script>
    <script>switchTheme(null);</script>
{% endblock %}
{% block scripts_app %}{% endblock %}
{% block scripts_page %}{% endblock %}
{% block jquery %}{% endblock %}
</html>

templates/partials/footer.html
<p class="copyright" style="z-index:30;">&copy; 2017, <b>Kelompok 9 PPW-E Gasal.</b></p>